"""fix agent_turns unique constraint to include session_id

Revision ID: b3722531725d
Revises: 1238462fe568
Create Date: 2026-05-27 10:15:30.616642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3722531725d'
down_revision: Union[str, Sequence[str], None] = '1238462fe568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_turns_agent_id_turn_number_key'), 'agent_turns', type_='unique')
    op.create_unique_constraint(None, 'agent_turns', ['session_id', 'agent_id', 'turn_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_turns', type_='unique')
    op.create_unique_constraint(op.f('agent_turns_agent_id_turn_number_key'), 'agent_turns', ['agent_id', 'turn_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
